version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/gabo-client"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/gabo-server"
    schedule:
      interval: "daily"